import {test,expect,type Page} from '@playwright/test';
import {unzipSync,strFromU8} from 'fflate';
import {readFile} from 'node:fs/promises';
async function photos(page:Page,count:number,start=0){return page.evaluate(({count,start})=>Array.from({length:count},(_,j)=>{const i=j+start;const canvas=document.createElement('canvas');canvas.width=96;canvas.height=128;const ctx=canvas.getContext('2d')!;ctx.fillStyle=`hsl(${i*29},30%,40%)`;ctx.fillRect(0,0,96,128);ctx.fillStyle='#fff';ctx.fillRect(15+i,20,35,65);return {name:`mock-${i}.png`,base64:canvas.toDataURL('image/png').split(',')[1]};}),{count,start});}
async function upload(page:Page,count:number,start=0){const files=await photos(page,count,start);await page.getByLabel('Add photographs',{exact:true}).setInputFiles(files.map(f=>({name:f.name,mimeType:'image/png',buffer:Buffer.from(f.base64,'base64')})));}
test('mobile: 1/10/11 uploads, classification, presets, save reload, export and fallback',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:/A true reference/})).toBeVisible();await page.screenshot({path:'work/mobile-empty.png',fullPage:true});
 await upload(page,1);await expect(page.getByText('1 / 10',{exact:true})).toBeVisible();await upload(page,9,1);await expect(page.getByText('10 / 10',{exact:true})).toBeVisible();await upload(page,1,10);await expect(page.getByRole('alert')).toContainText('Maximum 10');await expect(page.getByText('10 / 10',{exact:true})).toBeVisible();
 await page.getByLabel('Photo type 1',{exact:true}).selectOption('Front Face');await page.getByLabel('Photo type 2',{exact:true}).selectOption('Three-Quarter Face');await page.getByLabel('Photo type 3',{exact:true}).selectOption('Full Body Front');await page.getByLabel('Subject name',{exact:true}).fill('Subject A');await page.getByLabel('Sheet preset',{exact:true}).selectOption('Café Staff Character Sheet');await page.getByLabel('I confirm').check();
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect(page.getByText(/Draft saved on this browser/)).toBeVisible();await page.reload();await page.getByRole('button',{name:'Recent',exact:true}).click();await page.getByRole('button',{name:'Open project',exact:true}).click();await expect(page.getByText('10 / 10',{exact:true})).toBeVisible();await expect(page.getByLabel('Subject name',{exact:true})).toHaveValue('Subject A');await expect(page.getByLabel('Photo type 1',{exact:true})).toHaveValue('Front Face');
 await page.getByRole('button',{name:'Preview sheet →',exact:true}).click();await expect(page.locator('pre')).toContainText('UNIFORM DETAIL');await expect(page.locator('pre')).toContainText('ONE person');await page.getByRole('button',{name:'Generate Character Sheet',exact:true}).click();await expect(page.getByRole('heading',{name:'Continue in ChatGPT',exact:true})).toBeVisible();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export for Café Meme Creator',exact:true}).click();const d=await pending;const files=unzipSync(await readFile((await d.path())!));const key=Object.keys(files).find(k=>k.endsWith('manifest.json'))!;const manifest=JSON.parse(strFromU8(files[key]));expect(manifest.characterSheet).toBeNull();expect(manifest.references.length).toBeGreaterThan(0);for(const ref of manifest.references)expect(files[`characters/subject-a/${ref.path}`].length).toBeGreaterThan(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'work/mobile-preview.png',fullPage:true});expect(errors).toEqual([]);
});
test('host extension contract: selected files upload then imageIds state then text follow-up',async({page})=>{
 await page.addInitScript(()=>{const calls:unknown[]=[];Object.assign(window,{testCalls:calls,openai:{theme:'light',uploadFile:async(file:File)=>{calls.push({event:'upload',name:file.name});return {fileId:`file-${file.name}`};},setWidgetState:(state:unknown)=>calls.push({event:'state',state}),sendFollowUpMessage:async(args:unknown)=>{calls.push({event:'message',args});}}});});
 await page.goto('/');await upload(page,1);await page.getByLabel('Photo type 1',{exact:true}).selectOption('Front Face');await page.getByLabel('Sheet preset',{exact:true}).selectOption('Portrait Identity Sheet');await page.getByLabel('I confirm').check();await page.getByRole('button',{name:'Preview sheet →',exact:true}).click();await page.getByRole('button',{name:'Generate Character Sheet',exact:true}).click();await expect(page.getByText(/Request sent to ChatGPT/)).toBeVisible();const calls=await page.evaluate(()=>Reflect.get(window,'testCalls')) as {event:string;state?:{imageIds:string[]};args?:{prompt:string}}[];expect(calls.map(c=>c.event)).toEqual(['upload','state','message']);expect(calls[1].state?.imageIds).toEqual(['file-mock-0.png']);expect(calls[2].args).not.toHaveProperty('attachments');expect(calls[2].args?.prompt).toContain('ONLY the 1 selected');await page.screenshot({path:'work/light-preview.png',fullPage:true});
});
test('desktop and duplicate/unsupported photo errors',async({page})=>{await page.setViewportSize({width:1440,height:1000});await page.goto('/');await page.screenshot({path:'work/desktop-empty.png',fullPage:true});await upload(page,1);await upload(page,1);await expect(page.getByRole('alert')).toContainText('Duplicate image');await page.getByLabel('Add photographs',{exact:true}).setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('not a photo')});await expect(page.getByRole('alert')).toContainText('Unsupported image');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
