import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newProject,assertUploadBatch,parseProject,type UploadedReference,presetNames} from '../shared/model';
import {selectReferences,validateProject} from '../shared/references';
import {buildSpecification,IDENTITY_LOCK} from '../shared/characterSheetPromptBuilder';
import {exportManifest} from '../shared/export';
function ref(i:number,classification:UploadedReference['classification']='Front Face'):UploadedReference{return {id:crypto.randomUUID(),filename:`mock-${i}.png`,size:100,mime:'image/png',hash:i.toString(16).padStart(64,'0'),role:'IDENTITY_REFERENCE',classification,notes:''};}
function project(n=1){const p=newProject();p.references=Array.from({length:n},(_,i)=>ref(i));p.primaryId=p.references[0]?.id||'';p.oneSubjectConfirmed=true;return p;}
test('one-image upload allowed',()=>assert.doesNotThrow(()=>assertUploadBatch([],project().references)));
test('ten-image upload allowed',()=>assert.doesNotThrow(()=>assertUploadBatch([],project(10).references)));
test('eleventh image rejected atomically',()=>assert.throws(()=>assertUploadBatch(project(10).references,[ref(11)]),/Maximum 10/));
test('duplicates rejected',()=>assert.throws(()=>assertUploadBatch(project().references,[ref(0)]),/Duplicate/));
test('classification preserved by serialization',()=>{const p=project();p.references[0].classification='Right Profile';assert.equal(parseProject(JSON.parse(JSON.stringify(p))).references[0].classification,'Right Profile');});
test('ranking caps groups and ranks primary first',()=>{const p=project(10);p.primaryId=p.references[3].id;p.references[5].classification='Full Body Front';p.references[6].classification='Full Body Side';p.references[7].classification='Full Body Rear';p.references[8].classification='Hair Detail';p.references[9].classification='Clothing Detail';const r=selectReferences(p);assert.equal(r.length,7);assert.equal(r[0].id,p.primaryId);assert(!r.some(x=>x.classification==='Full Body Rear'));assert(r.some(x=>x.classification==='Hair Detail'));});
test('primary face priority overrides photograph order',()=>{const p=project(3);p.primaryId=p.references[2].id;assert.equal(selectReferences(p)[0].id,p.primaryId);});
test('manual selection remains authoritative',()=>{const p=project(5);p.selectionMode='manual';p.selectedReferenceIds=[p.primaryId,p.references[4].id];assert.deepEqual(selectReferences(p).map(r=>r.id),p.selectedReferenceIds);});
test('prompt deterministic with all fifteen sections',()=>{const p=project();const a=buildSpecification(p);assert.equal(a.prompt,buildSpecification(p).prompt);for(const title of ['TASK','IDENTITY REQUIREMENT','SUBJECT METADATA','REFERENCE PRIORITY','CHARACTER SHEET FORMAT','FULL BODY VIEWS','FACIAL DETAILS','CLOTHING / ACCESSORIES','CONSISTENCY RULES','LIGHTING','LAYOUT','ANATOMICAL QUALITY','TEXT LABELS','NEGATIVE CONSTRAINTS','FINAL PURPOSE'])assert(a.prompt.includes(title));});
test('metadata inserted without inventing blank fields',()=>{const p=project();p.subject={name:'Subject A',height:'185 cm',hair:'',glasses:''};const text=buildSpecification(p).prompt;assert(text.includes('Name: Subject A'));assert(text.includes('Height: 185 cm'));assert(!text.includes('Hair:'));assert(!text.includes('Glasses:'));});
test('presets switch without leaking uniform',()=>{const p=project();for(const preset of presetNames){p.preset=preset;assert(buildSpecification(p).prompt.includes(preset));}p.preset='Standard Character Sheet';assert(!buildSpecification(p).prompt.includes('M&S'));});
test('exact labels generated',()=>{const text=buildSpecification(project()).prompt;assert(text.includes('FRONT\nSIDE\nBACK\n3/4 VIEW\nEYES\nUPPER FACE\nLOWER FACE'));});
test('identity-lock remains present with prompt editing',()=>{const p=project();p.promptOverride='Custom instructions';assert(buildSpecification(p).prompt.startsWith(IDENTITY_LOCK));});
test('layout and foreign-role references never enter selection',()=>{const p=project(2);p.references[1].role='LAYOUT_REFERENCE';assert.equal(selectReferences(p).length,1);assert(validateProject(p).errors.some(e=>e.includes('identity photographs only')));assert(!buildSpecification(p).identityReferences.some(r=>r.id===p.references[1].id));});
test('project serialization round trip',()=>{const p=project(10);assert.deepEqual(parseProject(JSON.parse(JSON.stringify(p))),p);});
test('Café manifest has source refs but no fabricated generated image',()=>{const p=project();p.subject={name:'Subject A'};const m=exportManifest(p);assert.equal(m.id,'subject-a');assert.equal(m.characterSheet,null);assert.equal(m.generation.outputReceived,false);assert(m.references[0].path.startsWith('refs/'));});
test('handoff package separates identity from textual layout',()=>{const p=project(3);const spec=buildSpecification(p);assert.deepEqual(spec.referenceIds,selectReferences(p).map(r=>r.id));assert.deepEqual(spec.nonIdentityReferences,[]);assert.equal(spec.textualSheetSpecification.preset,p.preset);assert(!('attachments' in spec));});
test('one subject confirmation required',()=>{const p=project();p.oneSubjectConfirmed=false;assert(validateProject(p).errors.length);});
test('portrait single photo allowed with limited coverage warning',()=>{const p=project();p.preset='Portrait Identity Sheet';assert.deepEqual(validateProject(p).errors,[]);assert(validateProject(p).warnings.length);assert(buildSpecification(p).prompt.includes('Do not claim a reliable rear-body view'));});
test('acceptance fixture: staff subject metadata and views',()=>{const p=project(4);p.subject={name:'Piero',height:'6\'1"',build:'Tall, broad shoulders'};p.preset='Café Staff Character Sheet';p.references[1].classification='Three-Quarter Face';p.references[2].classification='Left Profile';p.references[3].classification='Full Body Front';const text=buildSpecification(p).prompt;for(const required of ['Piero','Tall, broad shoulders','ONE person','UNIFORM DETAIL','3/4 VIEW','correct shoulder placement'])assert(text.includes(required));assert(!/\bTom\b/.test(text));for(const field of ['Glasses:','Facial Hair:','Hair:'])assert(!text.includes(field));});
test('acceptance fixture: woman has no inherited template identity',()=>{const p=project(3);p.subject={sex:'Woman'};const text=buildSpecification(p).prompt;assert(text.includes('Sex: Woman'));assert(text.includes('all layout instructions are textual'));assert(text.includes('exaggerate masculinity or femininity'));assert(!/\bTom\b|\bPiero\b/.test(text));});
