import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { registerAppResource,registerAppTool,RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { projectSchema,parseProject } from '../shared/model';
import { validateProject } from '../shared/references';
import { buildSpecification } from '../shared/characterSheetPromptBuilder';
const html=readFileSync('dist/index.html','utf8');const build=JSON.parse(readFileSync('dist/build.json','utf8')) as {buildId:string;commit:string};const uri=`ui://character-sheet/editor-${build.commit}.html`;
export function createMcpServer(){const server=new McpServer({name:'character-sheet-generator',version:'1.0.0'});
 registerAppResource(server,'Character Sheet Editor',uri,{},async()=>({contents:[{uri,mimeType:RESOURCE_MIME_TYPE,text:html,_meta:{ui:{prefersBorder:false,csp:{connectDomains:[],resourceDomains:[]},...(process.env.WIDGET_ORIGIN?{domain:process.env.WIDGET_ORIGIN}:{})},'openai/widgetDescription':'Private character reference editor. User selects subject photos, metadata and textual layout; no visual layout references or image API.'}}]}));
 registerAppTool(server,'open_character_sheet',{title:'Open Character Sheet Generator',description:'Use this when the user wants to create a master character reference sheet from photographs of one subject. Opens the editor. Ask the user to add target-subject photographs in the widget.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{ui:{resourceUri:uri},'openai/widgetAccessible':true}},async()=>({content:[{type:'text',text:'Add 1–10 photographs of ONE subject in the editor. The layout is defined in text only.'}],structuredContent:{build:build.buildId,ready:true}}));
 server.registerTool('prepare_character_sheet',{title:'Prepare character sheet request',description:'Use this when the user has reviewed a Character Sheet Generator project and wants its selected-reference specification. Pure preparation; does not generate images or fetch photos.',inputSchema:{project:projectSchema},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true}},async({project})=>{const p=parseProject(project);const validation=validateProject(p);if(validation.errors.length)return {isError:true,content:[{type:'text',text:validation.errors.join(' ')}]};const spec=buildSpecification(p);return {structuredContent:{...spec},content:[{type:'text',text:spec.prompt}]};});return server;}
const port=Number(process.env.PORT||4318);const hostname=process.env.HOST||'127.0.0.1';
if(!['127.0.0.1','localhost','::1'].includes(hostname))throw Error('V1 is local-only. Add an authenticated deployment before binding publicly.');
createServer(async(req,res)=>{try{const pathname=new URL(req.url||'/',`http://localhost:${port}`).pathname;res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.method==='GET'&&pathname==='/'){res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);return;}if(req.method==='GET'&&pathname==='/health'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,build:build.buildId}));return;}if(pathname==='/mcp'&&req.method==='POST'){const server=createMcpServer();const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});res.on('close',()=>{void transport.close();void server.close();});await server.connect(transport);await transport.handleRequest(req,res);return;}res.writeHead(pathname==='/mcp'?405:404).end('Not available');}catch{if(!res.headersSent)res.writeHead(500);res.end('Request failed. Check the project and retry.');}}).listen(port,hostname,()=>console.log(`Character Sheet Generator: http://${hostname}:${port}\nMCP: http://${hostname}:${port}/mcp`));
