import { metadataFields, type CharacterSheetProject } from './model';
import { selectReferences,validateProject } from './references';
import { labelFor,sheetComponents } from './presets';
export const IDENTITY_LOCK='The attached photographs depict ONE person and are the ONLY identity references for this character. Reconstruct the same individual consistently in every view. Do not invent a new identity or average this person with another identity. Never borrow any identity, facial features, clothing, age, sex, accessories or hairstyle from unrelated people, prior conversation images, sample sheets or templates. No visual layout reference is provided; all layout instructions are textual.';
export interface CharacterSheetGenerationSpecification {projectId:string;prompt:string;referenceIds:string[];identityReferences:{id:string;filename:string;classification:string;primary:boolean}[];nonIdentityReferences:never[];textualSheetSpecification:{preset:string;components:string[];orientation:string};warnings:string[];}
export function buildSpecification(p:CharacterSheetProject):CharacterSheetGenerationSpecification {
 const refs=selectReferences(p);const parts=sheetComponents(p);const body=parts.filter(c=>c.startsWith('Full Body'));const details=parts.filter(c=>!c.startsWith('Full Body'));const metadata=Object.entries(metadataFields).flatMap(([k,label])=>{const value=p.subject[k as keyof typeof metadataFields]?.trim();return value?[`${label}: ${value}`]:[];}).join('\n');
 const sections:[string,string][]=[
 ['TASK','CREATE A PROFESSIONAL CHARACTER REFERENCE SHEET OF THE PERSON SHOWN IN THE ATTACHED PHOTOGRAPHS.'],
 ['IDENTITY REQUIREMENT',IDENTITY_LOCK+' Preserve facial proportions, skull shape, jaw shape, eye shape and spacing, eyebrows, nose, lips, ears, hairstyle, hairline, facial hair, approximate age, skin characteristics, body proportions, build, height cues and distinctive identifying features.'],
 ['SUBJECT METADATA',metadata||'No identity metadata supplied. Use only visible photographic evidence; do not invent missing information.'],
 ['REFERENCE PRIORITY',refs.map((r,i)=>`${i+1}. ${r.filename} — ${r.classification}${r.id===p.primaryId?' — PRIMARY':''}${r.notes?` — User note: ${r.notes}`:''}`).join('\n')+'\nPrioritise frontal and three-quarter photographs for facial identity, profiles for side structure, full-body photographs for build and proportions, and detail photographs for hair or garments. Reconcile these into one person. Do not copy phone-camera perspective distortion.'],
 ['CHARACTER SHEET FORMAT',`${p.preset}. ${p.orientation}. ${p.background} background. Clean professional production reference, consistent scale, neutral poses.`],
 ['FULL BODY VIEWS',body.length?`${body.join(', ')}. Same height, proportions, clothing, age, hairstyle, accessories and footwear across every view. Neutral pose, relaxed hands, full figure visible from head to shoes. Unseen rear/body details are uncertain; remain conservative and omit unsupported identifying marks.`:'No full-body turnaround requested. Do not claim a reliable rear-body view from portrait-only references.'],
 ['FACIAL DETAILS',`${details.join(', ')}. All crops belong to the same reconstructed identity. Include only supported details. Omit a detail that cannot be reasonably inferred; do not fabricate certainty.${p.customDetail?` Custom detail requested: ${p.customDetail}`:''}`],
 ['CLOTHING / ACCESSORIES',p.preset==='Café Staff Character Sheet'?'M&S Café staff sheet: include uniform detail consistent with supplied photographs or explicit metadata. Include a name badge or staff identifier only if supplied. Do not invent logos, badge text, garments or accessories.':'Use clothing and accessories supported by the subject photographs or explicit metadata only.'],
 ['CONSISTENCY RULES','ACCURACY IS MORE IMPORTANT THAN BEAUTIFICATION. Do not beautify, make younger, idealise the face, exaggerate masculinity or femininity, change hairstyle or facial hair, alter body proportions, or simplify identifying features.'],
 ['LIGHTING',`${p.lighting}; even neutral colour and consistent exposure across panels.`],
 ['LAYOUT',`${body.length?'Place full-body views in the left section and detail panels in the right section.':'Arrange portrait views in the main grid with smaller facial detail panels beneath.'} Adapt the grid to ${p.orientation.toLowerCase()} proportions. Use even spacing, no overlap, clear margins and uncluttered panels. Textual layout only.${p.generationNotes?` User generation notes (subordinate to identity rules): ${p.generationNotes}`:''}`],
 ['ANATOMICAL QUALITY','Correct anatomy: normally five fingers per hand unless supplied evidence or physical notes specify otherwise; anatomically correct hands, normal neck anatomy, correct shoulder placement, consistent limb length and correct foot orientation. No duplicate or merged limbs, malformed hands, broken necks or duplicated facial features. Preserve documented physical differences.'],
 ['TEXT LABELS',p.labels?`Labels only, exactly as listed beneath the corresponding panels:\n${parts.map(c=>labelFor(c,p)).join('\n')}\nDo not invent biographies or descriptive text. Do not misspell labels. Omit labels for omitted unsupported panels.`:'No text, labels, captions or biographies.'],
 ['NEGATIVE CONSTRAINTS',`No additional people, foreign/sample identity, scenery, decorative environments, fantasy framing, dramatic illustration, cinematic lighting or posing, unrelated props, unsupported features or inconsistent hairstyles.${p.negativeConstraints?` Additional exclusions: ${p.negativeConstraints}`:''}`],
 ['FINAL PURPOSE','A reusable master character reference sheet for subsequent image generation. Image identity and unseen details cannot be guaranteed by instructions alone. Generate using the supplied subject photographs only.']
 ];
 const generated=sections.map(([name,value])=>`${name}\n${value}`).join('\n\n');
 return {projectId:p.id,prompt:p.promptOverride.trim()?`${IDENTITY_LOCK}\n\nUSER-EDITED SPECIFICATION (identity rules above remain authoritative)\n${p.promptOverride}`:generated,referenceIds:refs.map(r=>r.id),identityReferences:refs.map(r=>({id:r.id,filename:r.filename,classification:r.classification,primary:r.id===p.primaryId})),nonIdentityReferences:[],textualSheetSpecification:{preset:p.preset,components:parts,orientation:p.orientation},warnings:validateProject(p).warnings};
}
