import { z } from 'zod';
export const classifications = ['Primary Face','Front Face','Three-Quarter Face','Left Profile','Right Profile','Full Body Front','Full Body Three-Quarter','Full Body Side','Full Body Rear','Hair Detail','Clothing Detail','Expression','Other Identity Reference'] as const;
export const roles = ['IDENTITY_REFERENCE','CLOTHING_REFERENCE','ACCESSORY_REFERENCE','LAYOUT_REFERENCE','ENVIRONMENT_REFERENCE'] as const;
export const presetNames = ['Standard Character Sheet','Portrait Identity Sheet','Full Production Sheet','Café Staff Character Sheet','Custom'] as const;
export const components = ['Full Body Front','Full Body Side','Full Body Back','Full Body 3/4','Portrait Front','Portrait Left 3/4','Portrait Right 3/4','Left Profile','Right Profile','Neutral Expression','Smile','Eyes','Upper Face','Lower Face','Nose','Mouth','Hair','Hairline','Skin','Hands','Footwear','Clothing','Accessory','Tattoo','Scar','Badge','Identifying Detail','Custom Detail'] as const;
export const metadataFields = {name:'Name',displayName:'Display Name',approximateAge:'Approximate Age',sex:'Sex',height:'Height',build:'Build',hair:'Hair',hairline:'Hairline',facialHair:'Facial Hair',eyes:'Eye Colour',glasses:'Glasses',skinTone:'Skin Tone',distinctiveFeatures:'Distinctive Features',clothing:'Default Clothing',jewellery:'Jewellery',tattoos:'Tattoos',scars:'Scars',mobility:'Mobility / Physical Notes',notes:'Other Notes'} as const;
const text = z.string().max(4000);
export const referenceSchema = z.object({id:z.string().uuid(),filename:z.string().min(1).max(255),mime:z.enum(['image/jpeg','image/png','image/webp']),size:z.number().int().positive().max(20*1024*1024),hash:z.string().regex(/^[a-f0-9]{64}$/),role:z.enum(roles),classification:z.enum(classifications),notes:text});
export const projectSchema = z.object({version:z.literal(1),id:z.string().uuid(),title:text,subject:z.object(Object.fromEntries(Object.keys(metadataFields).map(k=>[k,text.optional()]))),references:z.array(referenceSchema).max(10),primaryId:z.string(),selectionMode:z.enum(['auto','manual']),selectedReferenceIds:z.array(z.string()).max(10),oneSubjectConfirmed:z.boolean(),preset:z.enum(presetNames),orientation:z.enum(['Landscape','Portrait','Square']),background:z.enum(['White','Very Pale Neutral','Light Grey']),lighting:z.enum(['Neutral Studio','Soft Diffused Studio']),detailOptions:z.array(z.enum(components)),labels:z.boolean(),customDetail:text,generationNotes:text,negativeConstraints:text,promptOverride:z.string().max(30000),createdAt:z.string(),updatedAt:z.string()});
export type UploadedReference=z.infer<typeof referenceSchema>;
export type SubjectMetadata=Partial<Record<keyof typeof metadataFields,string>>;
export type CharacterSheetProject=Omit<z.infer<typeof projectSchema>,'subject'> & {subject:SubjectMetadata};
export function newProject():CharacterSheetProject {const now=new Date().toISOString();return {version:1,id:crypto.randomUUID(),title:'Untitled character',subject:{},references:[],primaryId:'',selectionMode:'auto',selectedReferenceIds:[],oneSubjectConfirmed:false,preset:'Standard Character Sheet',orientation:'Landscape',background:'White',lighting:'Neutral Studio',detailOptions:['Full Body Front','Full Body Side','Full Body Back','Full Body 3/4','Eyes','Hair','Skin','Clothing'],labels:true,customDetail:'',generationNotes:'',negativeConstraints:'',promptOverride:'',createdAt:now,updatedAt:now};}
export function parseProject(input:unknown):CharacterSheetProject{return projectSchema.parse(input) as CharacterSheetProject;}
export const MAX_IMAGES=10;
export function assertUploadBatch(existing:UploadedReference[],incoming:UploadedReference[]){if(existing.length+incoming.length>MAX_IMAGES)throw Error('Maximum 10 images. Remove a photograph before adding more.');const hashes=new Set(existing.map(r=>r.hash));for(const ref of incoming){referenceSchema.parse(ref);if(hashes.has(ref.hash))throw Error(`Duplicate image: ${ref.filename}`);hashes.add(ref.hash);}}
