import { parseProject, type CharacterSheetProject } from './model';
import { sheetComponents } from './presets';
export function selectReferences(p:CharacterSheetProject){
 const refs=p.references.filter(r=>r.role==='IDENTITY_REFERENCE');
 if(p.selectionMode==='manual')return refs.filter(r=>p.selectedReferenceIds.includes(r.id)).sort((a,b)=>Number(b.id===p.primaryId)-Number(a.id===p.primaryId));
 const face=['Primary Face','Front Face','Three-Quarter Face','Left Profile','Right Profile'];const body=['Full Body Front','Full Body Three-Quarter','Full Body Side','Full Body Rear'];const detail=['Hair Detail','Clothing Detail','Expression','Other Identity Reference'];
 const ranked=(list:string[])=>refs.filter(r=>list.includes(r.classification)).sort((a,b)=>Number(b.id===p.primaryId)-Number(a.id===p.primaryId)||list.indexOf(a.classification)-list.indexOf(b.classification));
 const primary=refs.find(r=>r.id===p.primaryId);const result=primary?[primary]:[];
 for(const [group,limit] of [[face,4],[body,2],[detail,1]] as const){const taken=result.filter(r=>group.includes(r.classification)).length;for(const r of ranked([...group]).filter(r=>!result.includes(r)).slice(0,limit-taken))result.push(r);}
 return result;
}
export function validateProject(input:CharacterSheetProject){const p=parseProject(input);const errors:string[]=[];const warnings:string[]=[];if(!p.references.length)errors.push('Add at least one photograph.');if(p.references.some(r=>r.role!=='IDENTITY_REFERENCE'))errors.push('Version 1 accepts target-subject identity photographs only. Remove non-identity references.');if(!p.oneSubjectConfirmed)errors.push('Confirm that all photographs depict ONE subject.');if(!p.references.some(r=>r.id===p.primaryId))errors.push('Select a primary identity reference.');if(new Set(p.references.map(r=>r.hash)).size!==p.references.length)errors.push('Remove duplicate images.');if(new Set(p.references.map(r=>r.id)).size!==p.references.length)errors.push('Reference IDs must be unique.');if(p.selectionMode==='manual'&&p.selectedReferenceIds.some(id=>!p.references.some(r=>r.id===id)))errors.push('A selected reference no longer exists.');const selected=selectReferences(p);if(!selected.length)errors.push('Select at least one identity reference.');if(!selected.some(r=>r.id===p.primaryId))errors.push('Include your primary reference in the selection.');if(p.preset==='Custom'&&!p.detailOptions.length)errors.push('Choose at least one custom sheet component.');const faces=selected.filter(r=>['Primary Face','Front Face','Three-Quarter Face','Left Profile','Right Profile'].includes(r.classification));if(faces.length<=1)warnings.push('Only one or no classified facial reference is available. Likeness consistency may be reduced.');if(!selected.some(r=>['Primary Face','Front Face'].includes(r.classification)))warnings.push('No frontal face is classified. Check your selected photographs.');if(sheetComponents(p).some(c=>c.startsWith('Full Body'))&&!selected.some(r=>r.classification.startsWith('Full Body')))warnings.push('No full-body reference is classified. Unseen body and rear views cannot be reliably inferred.');return {errors,warnings};}
