import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {classifications,components,metadataFields,newProject,presetNames,type CharacterSheetProject,type UploadedReference} from '../shared/model';
import {buildSpecification} from '../shared/characterSheetPromptBuilder';
import {selectReferences,validateProject} from '../shared/references';
import {sheetComponents,labelFor} from '../shared/presets';
import {store,exportCafe,download} from './storage';
import {readImages} from './uploads';
import {ChatGPTConversationProvider,connectHost} from './bridge';
import './styles.css';
declare const __BUILD__:string;
const provider=new ChatGPTConversationProvider();
function Thumbnail({blob,name}:{blob?:Blob;name:string}){const [url,setUrl]=useState('');useEffect(()=>{if(!blob)return;const value=URL.createObjectURL(blob);setUrl(value);return()=>URL.revokeObjectURL(value);},[blob]);return url?<img src={url} alt={name}/>:<span className="missing">Photo unavailable</span>;}
function Editor(){const [p,setP]=useState(newProject);const [assets,setAssets]=useState(new Map<string,Blob>());const [view,setView]=useState<'quick'|'full'|'templates'|'recent'|'preview'>('quick');const [status,setStatus]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [manual,setManual]=useState(false);const [projects,setProjects]=useState<CharacterSheetProject[]>([]);const [templates,setTemplates]=useState<Awaited<ReturnType<typeof store.templates>>>([]);const [templateName,setTemplateName]=useState('');const [editingPrompt,setEditingPrompt]=useState(false);const uploadRef=useRef<HTMLInputElement>(null);const operation=useRef(false);
 useEffect(()=>{void connectHost(setStatus);const sync=()=>{if(window.openai?.theme)document.documentElement.dataset.theme=window.openai.theme;};sync();window.addEventListener('openai:set_globals',sync);return()=>window.removeEventListener('openai:set_globals',sync);},[]);
 function patch(change:Partial<CharacterSheetProject>){setManual(false);setP(old=>({...old,...change,updatedAt:new Date().toISOString()}));}
 async function run(fn:()=>Promise<void>){if(operation.current)return;operation.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please retry.');}finally{operation.current=false;setBusy(false);}}
 async function upload(files:File[],replaceId?:string){await run(async()=>{const existing=p.references.filter(r=>r.id!==replaceId);const incoming=await readImages(files,existing);const next=new Map(assets);if(replaceId)next.delete(replaceId);for(const [id,blob] of incoming.blobs)next.set(id,blob);let refs=[...existing,...incoming.refs];if(replaceId){const old=p.references.find(r=>r.id===replaceId)!;const replacement={...incoming.refs[0],classification:old.classification,notes:old.notes};refs=p.references.map(r=>r.id===replaceId?replacement:r);}patch({references:refs,primaryId:p.primaryId===replaceId?incoming.refs[0].id:p.primaryId||incoming.refs[0]?.id||'',selectedReferenceIds:p.selectedReferenceIds.map(id=>id===replaceId?incoming.refs[0].id:id),oneSubjectConfirmed:false});setAssets(next);setStatus(`${incoming.refs.length} photograph${incoming.refs.length===1?'':'s'} added. Review the subject and classifications.`);});}
 function remove(ref:UploadedReference){const refs=p.references.filter(r=>r.id!==ref.id);patch({references:refs,primaryId:p.primaryId===ref.id?(refs[0]?.id||''):p.primaryId,selectedReferenceIds:p.selectedReferenceIds.filter(id=>id!==ref.id)});setAssets(old=>{const next=new Map(old);next.delete(ref.id);return next;});}
 function move(id:string,delta:number){const refs=[...p.references];const i=refs.findIndex(r=>r.id===id);const j=i+delta;if(j<0||j>=refs.length)return;[refs[i],refs[j]]=[refs[j],refs[i]];patch({references:refs});}
 async function save(){await run(async()=>{await store.saveDraft(p,assets);setStatus('Draft saved on this browser. Download an export for a portable backup.');});}
 async function openList(next:'templates'|'recent'){setView(next);await run(async()=>{if(next==='recent')setProjects(await store.list());else setTemplates(await store.templates());});}
 const selected=selectReferences(p);const specification=buildSpecification(p);const validation=validateProject(p);
 const subjectName=p.subject.displayName||p.subject.name||'Your character';
 const select=<label>Sheet preset<select aria-label="Sheet preset" value={p.preset} onChange={e=>patch({preset:e.target.value as CharacterSheetProject['preset']})}>{presetNames.map(name=><option key={name}>{name}</option>)}</select></label>;
 function section(title:string,content:React.ReactNode,open=false){return <details className="section" open={open||undefined}><summary>{title}<span>+</span></summary><div className="section-body">{content}</div></details>;}
 const photoControls=<><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void upload(Array.from(e.dataTransfer.files));}}><span className="photo-icon" aria-hidden="true">＋</span><h3>Start with the real person.</h3><p>Upload photographs of ONE subject only.</p><button className="primary" disabled={busy} onClick={()=>uploadRef.current?.click()}>Add photographs</button><small>1–10 photos · JPG, PNG, WebP · up to 20 MB each</small><input ref={uploadRef} aria-label="Add photographs" type="file" multiple accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{void upload(Array.from(e.target.files||[]));e.target.value='';}}/></div>{p.references.length>0&&<><div className="row"><h3>Identity references</h3><span className="pill">{p.references.length} / 10</span></div><div className="photos">{p.references.map((r,i)=><article className="photo" key={r.id}><div className="photo-image"><Thumbnail blob={assets.get(r.id)} name={r.filename}/><span className="photo-number">{String(i+1).padStart(2,'0')}</span></div><div className="photo-content"><p className="filename" title={r.filename}>{r.filename}</p><button className={p.primaryId===r.id?'selected':''} aria-pressed={p.primaryId===r.id} onClick={()=>patch({primaryId:r.id})}>{p.primaryId===r.id?'★ Primary reference':'Set as primary'}</button><label>Photo type<select aria-label={`Photo type ${i+1}`} value={r.classification} onChange={e=>patch({references:p.references.map(ref=>ref.id===r.id?{...ref,classification:e.target.value as UploadedReference['classification']}:ref)})}>{classifications.map(c=><option key={c}>{c}</option>)}</select></label>{view==='full'&&<label>Photo notes<input value={r.notes} onChange={e=>patch({references:p.references.map(ref=>ref.id===r.id?{...ref,notes:e.target.value}:ref)})}/></label>}<div className="photo-actions"><button aria-label={`Move photo ${i+1} earlier`} disabled={i===0} onClick={()=>move(r.id,-1)}>↑</button><button aria-label={`Move photo ${i+1} later`} disabled={i===p.references.length-1} onClick={()=>move(r.id,1)}>↓</button><label className="file-button">Replace<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])void upload([e.target.files[0]],r.id);e.target.value='';}}/></label><button className="danger" aria-label={`Delete photo ${i+1}`} onClick={()=>remove(r)}>Delete</button></div></div></article>)}</div><label className="check consent"><input type="checkbox" checked={p.oneSubjectConfirmed} onChange={e=>patch({oneSubjectConfirmed:e.target.checked})}/>I confirm these photographs depict ONE subject.</label></>}</>;
 return <main><header><div className="brand"><span className="brand-icon" aria-hidden="true">▦</span><div><strong>CHARACTER SHEET</strong><small>GENERATOR</small></div></div><span className="private-badge">Private studio</span></header><nav aria-label="Editor modes">{(['quick','full','templates','recent'] as const).map(item=><button key={item} aria-current={view===item?'page':undefined} className={view===item?'active':''} disabled={busy} onClick={()=>item==='templates'||item==='recent'?void openList(item):setView(item)}>{({quick:'Quick Sheet',full:'Full Editor',templates:'Templates',recent:'Recent'})[item]}</button>)}</nav>
 <div className="feedback" aria-live="polite">{status&&<p className="status">{status}</p>}{error&&<p role="alert" className="error">{error}</p>}</div>
 <fieldset disabled={busy} className="editor-fieldset">
 {(view==='quick'||view==='full')&&<><div className="hero"><div><p className="eyebrow">ONE PERSON. EVERY DETAIL.</p><h1>A true reference.<br/><span>From every angle.</span></h1><p className="subtitle">Keep the identity. Define the sheet.<br/>Let ChatGPT bring the views together.</p></div><div className="sheet-diagram" aria-label="Text-only sheet layout diagram"><div className="diagram-top">TEXTUAL LAYOUT <span>01</span></div><div className="diagram-grid">{['FRONT','SIDE','BACK','3/4 VIEW','EYES','HAIR'].map((t,i)=><div key={t}><span className={i<4?'diagram-bar':'diagram-detail'}/><small>{t}</small></div>)}</div><div className="diagram-bottom">NO SAMPLE IDENTITY</div></div></div>
 <div className="editor-columns"><div>{photoControls}</div><aside><section className="card"><p className="eyebrow">SUBJECT</p><h2>Who’s on the sheet?</h2><label>Subject name<input placeholder="Add a name (optional)" value={p.subject.name||''} onChange={e=>patch({subject:{...p.subject,name:e.target.value},title:e.target.value||'Untitled character'})}/></label>{select}<label>Generation notes <span className="optional">optional</span><textarea rows={3} placeholder="Anything the sheet should focus on?" value={p.generationNotes} onChange={e=>patch({generationNotes:e.target.value})}/></label><p className="hint">Only your subject photographs define identity. Sheet layouts are stored as text.</p></section>
 {section('Identity Lock',<div className="fields">{Object.entries(metadataFields).filter(([key])=>key!=='name').map(([key,label])=><label key={key}>{label}<input value={p.subject[key as keyof typeof metadataFields]||''} placeholder="Not specified" onChange={e=>patch({subject:{...p.subject,[key]:e.target.value}})}/></label>)}<p className="hint">Blank fields stay unspecified. No automatic identity or metadata guessing.</p></div>)}
 {section('Sheet details',<><div className="fields">{(['orientation','background','lighting'] as const).map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<select value={p[key]} onChange={e=>patch({[key]:e.target.value})}>{(key==='orientation'?['Landscape','Portrait','Square']:key==='background'?['White','Very Pale Neutral','Light Grey']:['Neutral Studio','Soft Diffused Studio']).map(s=><option key={s}>{s}</option>)}</select></label>)}</div><label className="check"><input type="checkbox" checked={p.labels} onChange={e=>patch({labels:e.target.checked})}/>Exact panel labels</label>{p.preset==='Custom'?<div className="component-options">{components.map(c=><label className="check" key={c}><input type="checkbox" checked={p.detailOptions.includes(c)} onChange={e=>patch({detailOptions:e.target.checked?[...p.detailOptions,c]:p.detailOptions.filter(x=>x!==c)})}/>{c}</label>)}</div>:<p className="hint">{sheetComponents(p).join(' · ')}</p>}<label>Custom detail<input value={p.customDetail} onChange={e=>patch({customDetail:e.target.value})}/></label><label>Additional exclusions<textarea value={p.negativeConstraints} onChange={e=>patch({negativeConstraints:e.target.value})}/></label></>)}
 {section('Reference selection',<><label>Selection mode<select value={p.selectionMode} onChange={e=>patch({selectionMode:e.target.value as 'auto'|'manual',selectedReferenceIds:selected.map(r=>r.id)})}><option value="auto">Automatic ranking</option><option value="manual">Choose references myself</option></select></label><p className="hint">Up to 4 face, 2 body and 1 detail photo. Your primary reference comes first. Classification is your choice.</p>{p.selectionMode==='manual'&&p.references.map(r=><label className="check" key={r.id}><input type="checkbox" checked={p.selectedReferenceIds.includes(r.id)} onChange={e=>patch({selectedReferenceIds:e.target.checked?[...p.selectedReferenceIds,r.id]:p.selectedReferenceIds.filter(id=>id!==r.id)})}/>{r.filename}</label>)}<strong>References that will be used</strong><div className="selected-photos">{selected.map(r=><div key={r.id}><Thumbnail blob={assets.get(r.id)} name={r.filename}/><small>{r.classification}</small></div>)}</div></>)}
 {section('Save as template',<><label>Template name<input value={templateName} onChange={e=>setTemplateName(e.target.value)}/></label><button disabled={!templateName.trim()} onClick={()=>void run(async()=>{await store.saveTemplate(p,templateName.trim());setStatus('Template saved. Subject identity and photographs are excluded.');})}>Save current settings as template</button></>)}
 </aside></div></>}
 {view==='preview'&&<><button className="back" onClick={()=>setView('full')}>← Back to editor</button><div className="page-heading"><p className="eyebrow">READY FOR CHATGPT</p><h1>{subjectName}</h1><p>{p.preset} · {p.orientation}</p></div><section className="card"><h2>References that will be used</h2><div className="selected-photos large">{selected.map(r=><div key={r.id}><Thumbnail blob={assets.get(r.id)} name={r.filename}/><small>{r.classification}{r.id===p.primaryId?' · Primary':''}</small></div>)}</div><dl>{Object.entries(p.subject).filter(([,value])=>value?.trim()).map(([key,value])=><React.Fragment key={key}><dt>{metadataFields[key as keyof typeof metadataFields]}</dt><dd>{value}</dd></React.Fragment>)}</dl><div className="labels">{sheetComponents(p).map(c=><span key={c}>{labelFor(c,p)}</span>)}</div></section><section className="card"><div className="row"><h2>Generated prompt</h2><button onClick={()=>{if(!editingPrompt)patch({promptOverride:specification.prompt});setEditingPrompt(!editingPrompt);}}> {editingPrompt?'Finish editing':'Edit prompt'}</button></div>{editingPrompt?<textarea className="prompt" aria-label="Edit generated prompt" value={p.promptOverride} onChange={e=>patch({promptOverride:e.target.value})}/>:<pre className="prompt">{specification.prompt}</pre>}<div className="button-row"><button onClick={()=>void run(async()=>{await navigator.clipboard.writeText(specification.prompt);setStatus('Prompt copied.');})}>Copy prompt</button><button onClick={()=>{patch({promptOverride:''});setEditingPrompt(false);}}>Regenerate prompt from settings</button><button onClick={()=>download(new Blob([specification.prompt],{type:'text/plain'}),'character-sheet-prompt.txt')}>Download prompt</button></div></section>{manual&&<section className="card manual"><h2>Continue in ChatGPT</h2><ol><li>Export the selected source photographs below and unzip the package.</li><li>Open a new ChatGPT conversation and attach the images in its refs folder.</li><li>Copy and paste this prompt, then ask ChatGPT to generate the sheet.</li></ol><p>Keep only this subject’s photographs in that conversation.</p></section>}<button onClick={()=>void run(async()=>{await exportCafe(p,assets);setStatus('Café export downloaded. No generated sheet is included until ChatGPT creates one.');})}>Export for Café Meme Creator</button></>}
 {view==='recent'&&<><div className="page-heading"><h1>Recent projects</h1><p>Saved in this browser. Host storage may be cleared; keep downloaded backups.</p></div><button onClick={()=>{setP(newProject());setAssets(new Map());setView('quick');}}>New character</button>{!projects.length&&<p className="empty">No saved projects yet. Use Save draft in the editor.</p>}{projects.map(project=><article className="card" key={project.id}><h2>{project.title}</h2><p>{project.preset} · {project.references.length} photographs</p><div className="button-row"><button onClick={()=>void run(async()=>{const saved=await store.load(project.id);if(!saved)throw Error('Draft no longer exists.');const blobs=await store.loadProjectAssets(project.id);setP(saved);setAssets(blobs);setView('full');setStatus('Draft loaded. Review photographs before generating.');})}>Open project</button><button onClick={()=>void run(async()=>{const copy={...project,id:crypto.randomUUID(),title:`${project.title} copy`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await store.saveDraft(copy,await store.loadProjectAssets(project.id));setProjects(await store.list());})}>Duplicate project</button><button className="danger" onClick={()=>void run(async()=>{await store.delete(project.id);setProjects(await store.list());setStatus('Saved project deleted from this browser.');})}>Delete saved project</button></div></article>)}</>}
 {view==='templates'&&<><div className="page-heading"><h1>A considered starting point.</h1><p>Textual layouts. No other person’s identity.</p></div><div className="template-grid">{presetNames.filter(n=>n!=='Custom').map((name,i)=><button className="template-card" key={name} onClick={()=>{patch({preset:name});setView('full');}}><span className="template-number">0{i+1}</span><h2>{name}</h2><p>{({ 'Standard Character Sheet':'Body turnaround + essential details','Portrait Identity Sheet':'Facial likeness comes first','Full Production Sheet':'Turnarounds, wardrobe + accessories','Café Staff Character Sheet':'Staff views + supplied uniform details'})[name as Exclude<typeof name,'Custom'>]}</p><span>Use template →</span></button>)}{templates.map(t=><button className="template-card" key={t.id} onClick={()=>{patch(t.settings);setView('full');}}><h2>{t.name}</h2><p>Saved settings · no subject photos</p><span>Use template →</span></button>)}</div></>}
 </fieldset>
 {(view==='quick'||view==='full'||view==='preview')&&<><div className="validation">{validation.errors.map(t=><p key={t} className="hint">○ {t}</p>)}{p.references.length>0&&validation.warnings.map(t=><p key={t} className="warning">△ {t}</p>)}</div><div className="sticky-actions"><div><strong>{selected.length} selected photo{selected.length===1?'':'s'}</strong><small>{busy?'Working…':'Identity references only'}</small></div><button disabled={busy} onClick={()=>void save()}>Save draft</button><button className="primary" disabled={busy||(view==='preview'&&validation.errors.length>0)} onClick={()=>{if(view!=='preview'){setView('preview');window.scrollTo({top:0});}else void run(async()=>{const result=await provider.send(p,assets);setStatus(result.message);setManual(!result.sent);});}}>{busy?'Working…':view==='preview'?'Generate Character Sheet':'Preview sheet →'}</button></div></>}
 <footer><p>Photos stay in this browser unless you generate through ChatGPT or download an export. No analytics. No image API billing.</p><small>Build {__BUILD__} · Build model: GPT-6 Astra</small></footer></main>;
}
createRoot(document.getElementById('root')!).render(<Editor/>);
