import {useState} from 'react';
import type {CharacterSheetProject} from '../shared/model';
import {selectReferences} from '../shared/references';
import {buildSpecification} from '../shared/characterSheetPromptBuilder';
import {download} from './storage';
export function MobileHandoff({project,assets}:{project:CharacterSheetProject;assets:Map<string,Blob>}){
 const [message,setMessage]=useState('');const refs=selectReferences(project);
 const files=refs.flatMap(ref=>{const blob=assets.get(ref.id);return blob?[new File([blob],ref.filename,{type:blob.type})]:[];});
 const canShare=files.length===refs.length&&files.length>0&&navigator.canShare?.({files});
 return <section className="card manual" id="mobile-handoff"><h2>Continue in ChatGPT</h2><p>Your draft is saved on this device. Complete these steps:</p><ol><li><strong>Copy the prompt.</strong> Use the button below.</li><li><strong>Open ChatGPT.</strong> Start a new conversation and attach the {refs.length} selected photo{refs.length===1?'':'s'} shown above, using your phone’s photo picker.</li><li><strong>Paste the prompt and send.</strong> Ask ChatGPT to create the sheet.</li></ol><div className="button-row"><button className="primary" onClick={()=>void navigator.clipboard.writeText(buildSpecification(project).prompt).then(()=>setMessage('Prompt copied. Now attach the selected photos in ChatGPT and paste it.')).catch(()=>setMessage('Copy was unavailable. Use the prompt text or Download prompt above.'))}>Copy prompt for ChatGPT</button><a className="link-button" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">Open ChatGPT ↗</a>{canShare&&<button onClick={()=>void navigator.share({files}).then(()=>setMessage('Photo share completed. Paste the copied prompt in ChatGPT.')).catch(error=>setMessage(error instanceof Error&&error.name==='AbortError'?'Sharing cancelled. You can still attach photos using ChatGPT’s picker.':'Photo sharing is unavailable. Use ChatGPT’s photo picker instead.'))}>Share selected photos</button>}</div><p className="hint">Sharing destinations depend on your phone. This app cannot automatically attach files to ChatGPT or press Send.</p><details><summary>Need a copy of the selected photos?</summary>{refs.map(ref=><button className="download-photo" key={ref.id} onClick={()=>{const blob=assets.get(ref.id);if(blob)download(blob,ref.filename);else setMessage('Photo missing. Return to the editor and re-add it.');}}>Download {ref.filename}</button>)}</details>{message&&<p role="status">{message}</p>}</section>;
}
